title: Home
description: Li Shunyang's Blog
base: /blog/
head:
  -
    - link
    - { rel: icon, href: /favicon.png }
themeConfig:
  nav:
    - text: Blog
      link: /blog/
    - text: About
      link: /about/
    - text: Github
      link: https://github.com/southerncross
  sidebar: auto
  lastUpdated: Last Updated
